config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :to_do_lists
  root "to_do_lists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/to_do_list.rb
class ToDoList < ApplicationRecord
end

app/models/to_do_sublist.rb
class ToDoSublist < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/to_do_lists_controller.rb
class ToDoListsController < ApplicationController
  def index
    @to_do_lists = ToDoList.all
  end

  def new
    @to_do_list = ToDoList.new
  end

  def create
    @to_do_list = ToDoList.new(to_do_list_params)
    if @to_do_list.save
      flash[:success] = 'To do list created successfully'
      render :show
    else
      flash[:error] = 'There is a problem in creating the to-do list'
      render :new
    end
  end

  def show
    @to_do_list = ToDoList.find(params[:id])
  end

  def edit
    @to_do_list = ToDoList.find(params[:id])
  end

  def update
    @to_do_list = ToDoList.find(params[:id])
    if @to_do_list.update(to_do_list_params)
      flash[:success] = 'To do list updated successfully'
      render :show
    else
      flash[:error] = 'There is a problem updating the to-do list'
      render :edit
    end
  end

  def destroy
    @to_do_list = ToDoList.find(params[:id])
    if @to_do_list.delete
      flash[:success] = 'To do list deleted successfully'
      redirect_to root_path
    else
      flash[:error] = 'There is a problem deleting the to-do list'
      render :show
    end

  end

  private
  def to_do_list_params
    params.require(:to_do_list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/to_do_helper.rb
module ToDoHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/to_do_lists/edit.html.erb
<div>
  <%= form_for @to_do_list do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.submit %>
  </p>
  <% end %>
</div>

app/views/to_do_lists/index.html.erb
<h1> Todo List </h1>
<a href="/to_do_lists/new"> <button >  Make a new list </button> </a>

<% if @to_do_lists %>
<ul>
  <% @to_do_lists.each do |list| %>
    <li>
      <%= link_to(list.name, to_do_list_path(list.id)) %>
    </li>
  <% end %>
</ul>
<% end %>

app/views/to_do_lists/new.html.erb
<div>
  <%= form_for @to_do_list do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.submit %>
  </p>
  <% end %>
</div>

app/views/to_do_lists/show.html.erb
<h1>
  <%= @to_do_list.name %>
  <%= button_to("delete", to_do_list_path(@to_do_list.id), method: :delete) %>
  <%= button_to("edit", edit_to_do_list_path(@to_do_list.id), method: :get) %>
  <%= button_to("back", to_do_lists_path, method: :get) %>
</h1>